language: java
jdk:
  - oraclejdk8
install: true

before_install:
  - npm install -g @angular/cli
  
  stages:
  - name: test
  - name: build

jobs:
  include:
      - stage: test
        script:
         - cd backend/airport-application-project
         - chmod +x mvnw
         - mvn test
         
      - stage: build
        script:
         - cd frontend
         - npm i
         - ng build --prod
         - cd ../backend/nokia-innovative-project
         - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
         
cache:
   directories:
    - $HOME/.m2