language: java
jdk:
  - oraclejdk8
install: true
before_install:
  - npm install -g @angular/cli
stages:
  - name: test
  - name: build
  - name: docker_build
    if: branch = master
  - name: deploy
    if: branch = master OR branch = develop
jobs:
  include:
      - stage: test
        script:
         - cd backend/airport-application-project
         - chmod +x mvnw
         - mvn test
      - stage: build
        script:
         - cd frontend/airport
         - npm i
         - ng build
         - cd -
         - cd backend/airport-application-project
         - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - stage: docker_build
        script:
          - cd backend/airport-application-project
          - mvn package
          - docker build -t $DOCKER_USERNAME/test:$BE_TAG .
          - cd -
          - cd frontend/airport
          - npm install
          - npm install @types/node --save-dev
          - npm run build
          - docker build -t $DOCKER_USERNAME/test:$FE_TAG .
          - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
          - docker push $DOCKER_USERNAME/test:$BE_TAG
          - docker push $DOCKER_USERNAME/test:$FE_TAG
      - stage: deploy
        script:
          - curl https://cli-assets.heroku.com/install-standalone.sh | sh
          - docker login --username=_ --password=$HEROKU_TOKEN registry.heroku.com
          - cd backend/airport-application-project
          - mvn package -DskipTests
          - docker build -t registry.heroku.com/wojtek-bakcio-test/web -f Dockerfile.prod .
          - cd -
          - cd frontend/airport
          - npm install
          - npm install @types/node --save-dev
          - ng build --prod
          - docker build -t registry.heroku.com/wojtek-froncio-test/web -f Dockerfile.prod .
          - docker push registry.heroku.com/wojtek-bakcio-test/web
          - docker push registry.heroku.com/wojtek-froncio-test/web
          - /usr/local/bin/heroku container:release web -a wojtek-bakcio-test
          - /usr/local/bin/heroku container:release web -a wojtek-froncio-test