language: java
jdk:
  - oraclejdk8
install: true
before_install:
  - npm install -g @angular/cli
stages:
  - name: test
  - name: build
  - name: docker_build
    if: branch = master
jobs:
  include:
      - stage: test
        script:
         - cd backend/airport-application-project
         - chmod +x mvnw
         - mvn test
      - stage: build
        script:
         - cd frontend/airport
         - npm i
         - ng build
         - cd -
         - cd backend/airport-application-project
         - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
         - stage: docker_build
        script:
          - cd backend/airport-application-project
          - mvn package
          - docker build -t $DOCKER_USERNAME/test:$TAG .
          - cd -
          - cd frontend/airport
          - npm install
          - npm install @types/node --save-dev
          - npm run build
          - docker build -t $DOCKER_USERNAME/test:$TAG .
          - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
          - docker push $DOCKER_USERNAME/test:$TAG          
          
          
          
          
          
          
          