language: java
jdk:
  - oraclejdk8
install: true

before_install:
  - npm install -g @angular/cli
  
  stages:
  - name: test

jobs:
  include:
      - stage: test
        script:
         - cd backend/airport-application-project
         - chmod +x mvnw
         - mvn test
         
cache:
   directories:
    - $HOME/.m2