spring:
  h2:
    console:
      enabled: true
      path: /h2-console
    datasource:
      platform: h2
      url: jdbc:h2:~/tim;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: sa
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: create-drop
        jdbc:
          lob:
            non_contextual_creation: true
      properties:
        higernate:
          temp:
            use_jdbc_metadata_defaults: false
    open-in-view: true
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
server:
  port: 8082