spring:
  datasource:
    url: jdbc:oracle:thin:@156.17.43.90:1521:xe
    username: pwr_17_18_L_016235902
    password: WojtasKradnieBazy666
    driver-class-name: oracle.jdbc.driver.OracleDriver
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        dialect: org.hibernate.dialect.Oracle12cDialect
        ddl-auto: create-drop
        jdbc:
          lob:
            non_contextual_creation: true
      properties:
        higernate:
          temp:
            use_jdbc_metadata_defaults: false
    open-in-view: true
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
server:
  port: 8082