spring:
  profiles:
    active: development
  mail:
    host: smtp.gmail.com
    port: 587
    username: airportservicesforapplication@gmail.com
    password: kokospoko1317
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true