liquibase:
  change-log: classpath:db/liquibase-changelog.xml
spring:
  profiles:
    active: development
  mail:
    host: smtp.gmail.com
    username: airportservicesforapplication@gmail.com
    password: kokospoko1317
    port: 587
    properties:
      mail:
        transport.protocol: smtp
        smtp:
          auth: true
          starttls.enable: true
    debug: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false