spring:
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        hbm2ddl:
          auto: create-drop
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        ddl-auto: create-drop
        jdbc:
          lob:
            non_contextual_creation: true
      properties:
        higernate:
          temp:
            use_jdbc_metadata_defaults: false
    open-in-view: false
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1