spring:
  datasource:
    url: jdbc:postgres://xghonjlapssiry:64e5deb49033e6566b1fb4e9cc2af54e2c3cdfd8db8bcbd5933c8dbef13ec86c@ec2-54-75-230-41.eu-west-1
    username: xghonjlapssiry
    password: 64e5deb49033e6566b1fb4e9cc2af54e2c3cdfd8db8bcbd5933c8dbef13ec86c
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        hbm2ddl:
          auto: create-drop
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        ddl-auto: create-drop
        jdbc:
          lob:
            non_contextual_creation: true
      properties:
        higernate:
          temp:
            use_jdbc_metadata_defaults: false
    open-in-view: false
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1